### PR TITLE
Fix: Generate project mvn settings files in maven verify workflow

### PR DESCRIPTION
**Pull request by jwagantall**
Use s4u/maven-settings-action to setup maven settings.xml The following variables need to be present in the project:
 - CONTAINER_PUBLIC_REGISTRY
 - CONTAINER_PULL_REGISTRY
 - CONTAINER_PUSH_REGISTRY
 - CONTAINER_STAGING_REGISTRY
 - DOCKERHUB_USER
 - NEXUS_ORG
 - NEXUS_USER
 - NEXUS3_USER And the following secrets need to be defined:
 - NEXUS3_READONLY_PASSWORD
 - NEXUS3_PASSWORD
 - DOCKERHUB_PASSWORD
 - NEXUS_PASSWORD

### CODE REVIEW

**Review by MightyNerdEric — CHANGES_REQUESTED** [review]
This is a pretty rigid way of doing this, and some projects won't have exactly those repos. I think it would be better to just require a project to store these as variables on Github, the same way that these are managed files on Jenkins.

**Comment by jwagantall** [comment]
@MightyNerdEric  thank you for your input. I think the biggest issue is having the settings constructed using these variables. Is there a way that we can take these servers/user/pass and add them to the project's global-settings file? If so we can pick them from there but not sure how the passwords would be introduced. 

Wouldn't it be nice if GH could store secret files? :)

**Comment by MightyNerdEric** [comment]
GH _can_ store secret files. For example, this is a replacement for creating the global settings file that I came up with:
```
      - name: Create global settings file
        run: |
          echo "${{ vars.MVN_GLOBAL_SETTINGS }}" > settings.xml
```

**Comment by jwagantall** [comment]
Oh,, I see... so MVN_GLOBAL_SETTINGS can contain a full file, with indentation and all ?

**Pull request closed without merging**
